#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

mysql -u $db_user -p${db_pwd} -e "UPDATE ${db_name}.grr_setting SET \`value\` = 'https://${new_domain}${new_path}' WHERE \`name\` = 'grr_url';"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
