#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config_ldap.inc.php" --destination="$install_dir/personnalisation/config_ldap.inc.php"
ynh_config_add --template="connect.inc.php" --destination="$install_dir/personnalisation/connect.inc.php"

mysql --default-character-set=latin1 -u $db_user -p${db_pwd} $db_name < $install_dir/installation/tables.my.sql

ynh_config_add --template="grr_ldap_sso.sql" --destination="/tmp/grr_ldap_sso.sql"
mysql -u $db_user -p${db_pwd} $db_name < /tmp/grr_ldap_sso.sql
rm /tmp/grr_ldap_sso.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
