#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="config_ldap.inc.php" --destination="$install_dir/personnalisation/config_ldap.inc.php"
ynh_config_add --template="connect.inc.php" --destination="$install_dir/personnalisation/connect.inc.php"

chmod 400 "$install_dir/personnalisation/config_ldap.inc.php"
chmod 400 "$install_dir/personnalisation/connect.inc.php"
chown $app:$app "$install_dir/personnalisation/config_ldap.inc.php"
chown $app:$app "$install_dir/personnalisation/connect.inc.php"

#=================================================
# UPDATE DATABASE
#=================================================
ynh_script_progression "Updating database..."

pushd $install_dir/installation
	ynh_write_var_in_file --file="$install_dir/installation/maj.php" --key="majscript" --value=true
	php${php_version} maj.php ""
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
